name: Mi workflow

on: push 

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps: 
      - name: Bajar código
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: Crear imagen docker
        run: docker build -t sergiom8m8/holamundo .

      - name: Probar imagen docker
        run: docker run sergiom8m8/holamundo
